added support for preferences update
nishantdania/quickbooks-ruby pull request #3
Opened 2021-06-22 06:21 UTC by Shirish-Peshwe

2021-06-29 01:48 UTC, nishantdania requested changes

2021-06-29 01:48 UTC, nishantdania commented on spec/lib/quickbooks/model/preferences_spec.rb
> +    binding.pry
Let's remove this

2021-06-29 03:33 UTC, Shirish-Peshwe commented on spec/lib/quickbooks/model/preferences_spec.rb
> +    binding.pry
Done

2021-06-30 00:54 UTC, nishantdania approved these changes
LGTM

2021-06-30 00:56 UTC, nishantdania commented
As a sidenote for future readers, roxml doesn't seem to have a way to send extra attributes in the generated xml which is needed for CustomFields to work since those fields expect a schema attribute to be send. We are disabling that part from the gem for now and will need to enable it and fix it in th future in case we want to use it.

2021-06-30 06:36 UTC, merged